In [36]:
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()
tf.set_random_seed(0)

In [31]:
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data  = [1, 2, 3, 4, 5]

learing_rate = tf.Variable(0.001)
#x_data = [x1_data,x2_data]

w1 = tf.Variable(tf.random_uniform([1],-10.0, 10.0)) #1차원 : vector 의 형태로 uniform 분포에서 random값 가져옴
w2 = tf.Variable(tf.random_uniform([1],-10.0, 10.0))

for i in range(1001):
    with tf.GradientTape() as tape:
        h = w1 * x1_data + w2 * x2_data
        cost = tf.reduce_mean(tf.square(h - y_data))
    w1_grad, w2_grad = tape.gradient(cost,[w1,w2])
    
    w1.assign_sub(learing_rate * w1_grad)
    w2.assign_sub(learing_rate * w2_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f}".format(
          i, cost.numpy(), w1.numpy()[0], w2.numpy()[0]))


    0 | 186.462006 |    -4.0883 |     1.1074
   50 |  45.537891 |    -1.5143 |     1.0719
  100 |  11.123245 |    -0.2424 |     1.0481
  150 |   2.717874 |     0.3861 |     1.0322
  200 |   0.664481 |     0.6966 |     1.0215
  250 |   0.162631 |     0.8501 |     1.0144
  300 |   0.039882 |     0.9259 |     1.0097
  350 |   0.009815 |     0.9634 |     1.0065
  400 |   0.002431 |     0.9819 |     1.0043
  450 |   0.000609 |     0.9911 |     1.0029
  500 |   0.000156 |     0.9956 |     1.0019
  550 |   0.000041 |     0.9978 |     1.0013
  600 |   0.000011 |     0.9989 |     1.0009
  650 |   0.000003 |     0.9995 |     1.0006
  700 |   0.000001 |     0.9997 |     1.0004
  750 |   0.000000 |     0.9999 |     1.0003
  800 |   0.000000 |     0.9999 |     1.0002
  850 |   0.000000 |     1.0000 |     1.0001
  900 |   0.000000 |     1.0000 |     1.0001
  950 |   0.000000 |     1.0000 |     1.0001
 1000 |   0.000000 |     1.0000 |     1.0000


In [36]:
x_data = [
    [1., 0., 3., 0., 5.],
    [0., 2., 0., 4., 0.]
]
w = tf.Variable(tf.random_uniform([1,2],-1.0,1.0))
b = tf.Variable(tf.random_uniform([1],-1.0,1.0))

for i in range(1001):
    with tf.GradientTape() as tape:
        h = tf.matmul(w,x_data) + b # [1,2] * [2.5] = [1,5]
        cost = tf.reduce_mean(tf.square(tf.subtract(h,y_data)))
    
        w_grad,b_grad = tape.gradient(cost,[w,b])
        w.assign_sub(learing_rate * w_grad)
        b.assign_sub(learing_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
            i, cost.numpy(), w.numpy()[0][0], w.numpy()[0][1], b.numpy()[0]))
        

    0 |  26.859333 |    -0.7834 |     0.5674 |  -0.388345
   50 |   5.932927 |     0.1461 |     0.7321 |  -0.095914
  100 |   1.321521 |     0.5795 |     0.8222 |   0.042908
  150 |   0.300822 |     0.7814 |     0.8729 |   0.108648
  200 |   0.072953 |     0.8754 |     0.9024 |   0.139428
  250 |   0.021219 |     0.9192 |     0.9200 |   0.153367
  300 |   0.009064 |     0.9396 |     0.9309 |   0.159121
  350 |   0.005992 |     0.9493 |     0.9379 |   0.160858
  400 |   0.005083 |     0.9540 |     0.9425 |   0.160599
  450 |   0.004722 |     0.9565 |     0.9456 |   0.159340
  500 |   0.004514 |     0.9579 |     0.9479 |   0.157575
  550 |   0.004355 |     0.9588 |     0.9496 |   0.155556
  600 |   0.004216 |     0.9596 |     0.9509 |   0.153414
  650 |   0.004085 |     0.9602 |     0.9521 |   0.151218
  700 |   0.003961 |     0.9608 |     0.9530 |   0.149005
  750 |   0.003842 |     0.9614 |     0.9539 |   0.146797
  800 |   0.003726 |     0.9620 |     0.9547 |   0.144603
  850 |   0.00

# Predicting exam score
regression using three inputs (x1, x2, x3)

x1 (quiz 1) | x2 (quiz 2) | x3 (mid 1) | Y (final)
---- | ---- | ----| ----
73 | 80 | 75 | 152
93 | 88 | 93 | 185
89 | 91 | 90 | 180
96 | 98 | 100 | 196
73 | 66 | 70 | 142

In [62]:
# data = np.array([
#     # X1,   X2,    X3,   y
#     [ 73.,  80.,  75., 152. ],
#     [ 93.,  88.,  93., 185. ],
#     [ 89.,  91.,  90., 180. ],
#     [ 96.,  98., 100., 196. ],
#     [ 73.,  66.,  70., 142. ]
# ], dtype=np.float32)

# # slice data
# x_data = data[:, :-1]
# y_data = data[:, [-1]]

x1_data = [73.,80.,75.]
x2_data = [93.,88.,93.]
x3_data = [89.,91.,90.]
x4_data = [96.,98.,100.]
x5_data = [73.,66.,70.]

x_data = [x1_data,x2_data,x3_data,x4_data,x5_data] # 5 by 3
y_data = [[152.],[185.],[180.],[196.],[142.]] # 1 by 5
#y_data = [152.,185.180.,196.,142.] --> 행렬이랑 계산될때 5 by 5 로 취급됨.

W = tf.Variable(tf.random_normal([3,1])) # Weight matrix, 3 by 1

print("epoch | cost | W_1 | W_2 | W_3")
for i in range(1001):
    with tf.GradientTape() as tape:
        h = tf.matmul(x_data,W) # matmul -> 행렬상으로 곱셈
        cost = tf.reduce_mean(tf.square(h - y_data))
    W_grad = tape.gradient(cost,W)
    W.assign_sub(0.000001 * W_grad)
        
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f} | {:10.4f} ".format(
            i, cost.numpy(),W_grad[0][0] ,W.numpy()[0][0], W.numpy()[1][0],W.numpy()[2][0]))


epoch | cost | W_1 | W_2 | W_3
    0 | 122742.421875 | -59792.2070 |    -0.2771 |    -1.2153 |    -0.4104 
   50 | 1364.798584 | -6293.7451 |     0.8846 |    -0.0540 |     0.7650 
  100 |  17.704073 |  -657.7603 |     1.0068 |     0.0687 |     0.8887 
  150 |   2.748055 |   -64.0282 |     1.0194 |     0.0820 |     0.9016 
  200 |   2.576383 |    -1.4856 |     1.0204 |     0.0838 |     0.9029 
  250 |   2.568840 |     5.0952 |     1.0203 |     0.0844 |     0.9029 
  300 |   2.563084 |     5.7812 |     1.0200 |     0.0848 |     0.9028 
  350 |   2.557387 |     5.8361 |     1.0197 |     0.0853 |     0.9026 
  400 |   2.551695 |     5.8426 |     1.0194 |     0.0857 |     0.9025 
  450 |   2.546045 |     5.8345 |     1.0191 |     0.0861 |     0.9024 
  500 |   2.540395 |     5.8200 |     1.0188 |     0.0865 |     0.9022 
  550 |   2.534762 |     5.8046 |     1.0185 |     0.0870 |     0.9021 
  600 |   2.529111 |     5.7853 |     1.0182 |     0.0874 |     0.9020 
  650 |   2.523479 |     5.7

In [61]:
W = tf.Variable(tf.random_normal([3,1])) # Weight matrix, 3 by 1

data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
x_data = data[:, :-1]
y_data = data[:, [-1]]

print(x_data)
print(y_data)
print(tf.matmul(x_data,W) - y_data)

x1_data = [73.,80.,75.]
x2_data = [93.,88.,93.]
x3_data = [89.,91.,90.]
x4_data = [96.,98.,100.]
x5_data = [73.,66.,70.]

x1_data = [x1_data,x2_data,x3_data,x4_data,x5_data] # 5 by 3
y1_data = [152.,185.,180.,196.,142.]

print(x1_data)
print(y1_data)
print(tf.matmul(x1_data,W) - y1_data)


[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]
tf.Tensor(
[[-405.4803 ]
 [-499.9943 ]
 [-484.83234]
 [-530.5787 ]
 [-382.6597 ]], shape=(5, 1), dtype=float32)
[[73.0, 80.0, 75.0], [93.0, 88.0, 93.0], [89.0, 91.0, 90.0], [96.0, 98.0, 100.0], [73.0, 66.0, 70.0]]
[152.0, 185.0, 180.0, 196.0, 142.0]
tf.Tensor(
[[-405.4803  -438.4803  -433.4803  -449.4803  -395.4803 ]
 [-466.9943  -499.9943  -494.9943  -510.9943  -456.9943 ]
 [-456.83234 -489.83234 -484.83234 -500.83234 -446.83234]
 [-486.57867 -519.5787  -514.5787  -530.5787  -476.57867]
 [-392.6597  -425.6597  -420.6597  -436.6597  -382.6597 ]], shape=(5, 5), dtype=float32)
