In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
tf.enable_eager_execution()
tf.set_random_seed(777)  # for reproducibility
tfe = tf.contrib.eager

In [34]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.asarray(x_data,dtype=np.float32) #asarray -> input을 array로 변환시킴
y_data = np.asarray(y_data,dtype=np.float32)

nb_classes = 3


<h1>Axis</h1>
<a href = "http://taewan.kim/post/numpy_sum_axis/">출처</a><br>
<img src = "https://taewanmerepo.github.io/2017/09/numpy_axis/axis.jpg"/>

axis에 따라 계산하는 방법이 달라짐.

<h2>example</h2><br>
<img src = "https://taewanmerepo.github.io/2017/09/numpy_axis/shape1.png" /><br>
<img src = "https://taewanmerepo.github.io/2017/09/numpy_axis/sample.jpg" /><br>

In [47]:
def hypothesis(x,W):
    return tf.nn.softmax(tf.matmul(x,W)+b)

def cost(Label,Y):
    return -tf.reduce_mean(tf.reduce_sum(Label * tf.log(Y), axis = 1))

def test(X):
    print(hypothesis(X,W))
    print(tf.argmax(hypothesis(X,W),1))

In [40]:
W = tfe.Variable(tf.random_normal([4,nb_classes]))
b = tfe.Variable(tf.random_normal([nb_classes]))

In [41]:
for i in range(2001):
    optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
    with tf.GradientTape() as tape:
        result = cost(y_data,hypothesis(x_data,W))
    grads = tape.gradient(result,[W,b])
    optimizer.apply_gradients(zip(grads,[W,b]))
    if i % 100 == 0:
        print("iter : {} loss : {:.4f}".format(i,result))

iter : 0 loss : 11.7785
iter : 100 loss : 0.7003
iter : 200 loss : 0.6308
iter : 300 loss : 0.5755
iter : 400 loss : 0.5257
iter : 500 loss : 0.4783
iter : 600 loss : 0.4319
iter : 700 loss : 0.3860
iter : 800 loss : 0.3403
iter : 900 loss : 0.2951
iter : 1000 loss : 0.2546
iter : 1100 loss : 0.2351
iter : 1200 loss : 0.2236
iter : 1300 loss : 0.2132
iter : 1400 loss : 0.2036
iter : 1500 loss : 0.1948
iter : 1600 loss : 0.1867
iter : 1700 loss : 0.1793
iter : 1800 loss : 0.1724
iter : 1900 loss : 0.1659
iter : 2000 loss : 0.1600


In [49]:
test([[1.,1.,1.,1.]])

tf.Tensor([[1.6042466e-05 3.3004205e-03 9.9668354e-01]], shape=(1, 3), dtype=float32)
tf.Tensor([2], shape=(1,), dtype=int64)


In [50]:
test([[1., 7., 7., 7.]])

tf.Tensor([[9.1593921e-01 8.4060505e-02 3.1977083e-07]], shape=(1, 3), dtype=float32)
tf.Tensor([0], shape=(1,), dtype=int64)


In [51]:
test(x_data)

tf.Tensor(
[[3.2735263e-06 1.0264806e-03 9.9897027e-01]
 [1.5652822e-03 8.4051616e-02 9.1438305e-01]
 [6.1209086e-08 1.6672978e-01 8.3327013e-01]
 [1.1919321e-06 8.4742862e-01 1.5257014e-01]
 [2.6057228e-01 7.2708237e-01 1.2345379e-02]
 [1.3707095e-01 8.6292309e-01 5.9813274e-06]
 [7.5072885e-01 2.4925147e-01 1.9656585e-05]
 [9.1593927e-01 8.4060431e-02 3.1977052e-07]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)
